@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
###
@authToken = {{login.response.body.token}}


####
// @route    POST api/auth
// @desc     Authenticate user & get token
// @access   Public
# @name login
POST {{host}}/api/auth HTTP/1.1
content-type: application/json

{
    "name":"Dereje",
    "email":"d@gmail.com",
    "password":"Dereje"
}


# ------------------------------------------------------
###
// @route    PUT api/contacts/:id
// @desc     Update a contact
// @access   Private
PUT {{host}}/api/contacts/5fd03e937f5e162dfcfe8140 HTTP/1.1
content-type: application/json
x-auth-token: {{authToken}}

{
    "name":"DerejeK",
    "type":"prof"
}
