@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
###
@authToken = {{login.response.body.token}}


####
// @route    POST api/auth
// @desc     Authenticate user & get token
// @access   Public
# @name login
POST {{host}}/api/auth HTTP/1.1
content-type: application/json

{
    "name":"Dereje",
    "email":"d@gmail.com",
    "password":"Dereje"
}

# ------------------------------------------------------
###
// @route    DELETE api/contacts/:id
// @desc     Delete a contact
// @access   Private
DELETE {{host}}/api/contacts/5fd03c1b7f5e162dfcfe813b HTTP/1.1
content-type: application/json
x-auth-token: {{authToken}}
