@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
###
@authToken = {{login.response.body.token}}


// @route    POST api/auth
// @desc     Authenticate user & get token
// @access   Public
####
# @name login
POST {{host}}/api/auth HTTP/1.1
content-type: application/json

{
    "name":"Dereje",
    "email":"d@gmail.com",
    "password":"Dereje"
}


// @route    GET api/auth
// @desc     Get logged user
// @access   Private
###
GET {{host}}/api/auth HTTP/1.1
x-auth-token: {{authToken}}



