@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
###
@authToken = {{login.response.body.token}}


// @desc    Auth user & get token
// @route   POST /api/users/login
// @access  Public
####
# @name login
POST {{host}}/api/users/login HTTP/1.1
content-type: application/json

{
    "name":"Dereje",
    "email":"d@gmail.com",
    "password":"Dereje"
}


// @desc    Delete a panel
// @route   DELETE /api/panels/:id
// @access  Private/Admin
###
DELETE  {{host}}/api/panels/5fd59576f1bfaa33f8147ef2 HTTP/1.1
authorization:  Bearer {{authToken}}


###
// @desc    Fetch all panels
// @route   GET /api/panels
// @access  Public
GET {{host}}/api/panels HTTP/1.1
authorization:  Bearer {{authToken}}
