@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
###
@authToken = {{login.response.body.token}}


// @desc    Auth user & get token
// @route   POST /api/users/login
// @access  Public
####
# @name login
POST {{host}}/api/users/login HTTP/1.1
content-type: application/json

{
    "name":"Dereje",
    "email":"d@gmail.com",
    "password":"Dereje"
}


// @desc    Get all users
// @route   GET /api/users
// @access  private/Admin
###
GET {{host}}/api/users HTTP/1.1
authorization:  Bearer {{authToken}}

